name = "Polisher-S6"
author = "devin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6309fcd21cab088b6ba1228526cb796eb40e3f0fbf7b16078a14df3313d0363"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
