name = "Polisher-S6"
author = "devin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93f0d833db6874be8f9b8c51dd1d43511d78c8611eb1b6c6c575581ff526bbf6"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
